context:
  version: 1.9.0

package:
  name: hereby
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/hereby/-/hereby-${{ version }}.tgz
  sha256: 982b00c8e1662f02318110312fc915aceac70e881fe41b6b491a57125ad67d3b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - hereby --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A simple Node.js task runner
  homepage: https://github.com/jakebailey/hereby
  repository: https://github.com/jakebailey/hereby

extra:
  recipe-maintainers:
    - danielnachun
