context:
  version: "1.15.1"

package:
  name: hereby
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/hereby/-/hereby-${{ version }}.tgz
  sha256: 91d1db9aa15f77b910682195ec597b143c9fd336e160d82962776b00da349b1a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - hereby --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A simple Node.js task runner
  homepage: https://github.com/jakebailey/hereby
  repository: https://github.com/jakebailey/hereby

extra:
  recipe-maintainers:
    - danielnachun
