context:
  version: "1.14.0"

package:
  name: hereby
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/hereby/-/hereby-${{ version }}.tgz
  sha256: fa988d16be56aaa0f6e3f2fcd81af31505312c2b256ae7be0e09f2e6d09a15dc

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - hereby --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A simple Node.js task runner
  homepage: https://github.com/jakebailey/hereby
  repository: https://github.com/jakebailey/hereby

extra:
  recipe-maintainers:
    - danielnachun
