context:
  version: "1.12.0"

package:
  name: hereby
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/hereby/-/hereby-${{ version }}.tgz
  sha256: 2151083d20a3fbf7826b8ac3eca7448f3f3b28824d006d587ea4d0aafd9c9aae

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - hereby --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A simple Node.js task runner
  homepage: https://github.com/jakebailey/hereby
  repository: https://github.com/jakebailey/hereby

extra:
  recipe-maintainers:
    - danielnachun
